version: '2'

services:
  pgdatabase: 
    image: postgres:13
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=db-name
    volumes:
      - ./data:/var/lib/postgresql/data
      #This stores the database on the local machine enabling data to persist between runs
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      #This allows the user to run SQL scripts on startup by putting the script in a ./sql directory
    ports:
        - "5433:5432"
        #Allows to map the containers 5433 port to the locals 5432 port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db-name -U db-user"]
      interval: 10s
      timeout: 5s
      retries: 5

  #This is a GUI for postgres    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      #Use these to log it to pgAdmin
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8888:80"
    depends_on:
      pgdatabase:
        condition: service_healthy

  ingestion_script:
    build: .
    volumes:
      - ./ny_taxi:/app/ny_taxi
    depends_on:
      pgdatabase:
        condition: service_healthy
    # This will build a local dockerfile and run it as a container, it will also create a volume in the repo where we can see the downloaded ny_taxi dataset file.